GET http://localhost:3001/customers/


###
GET http://localhost:3001/customers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im13YXMydmljIiwiaWQiOjIsImlhdCI6MTczMjc4NDk2OSwiZXhwIjoxNzMyNzg1MDM5fQ.B7BwXQduOMYpwkaxlgw1ytGxhHbJ1pFFj7jczrVrUIQ
###
POST http://localhost:3001/customers/
Content-Type: application/json

{
	"firstname":"mwas2",
	"lastname": "vic",
    "username":"mwas2vic",
	"email":"mwasvic2@gmail.com",
	"password":"Kami1234"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "username": "mwas2vic",
  "password":"Kami1234"

}

###

POST http://localhost:3001/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im13YXMydmljIiwiaWQiOjIsImlhdCI6MTczMjc4NTQ4OX0.rs-gxy0ZlSqJy2PBecxave7_gwGnooENo4A-u8pv4XM"
}